apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: discordapp-clone
spec:
  secretName: discordapp-clone-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: discordapp-clone.com
    dnsNames:
      - discordapp-clone.com
      - www.discordapp-clone.com
    acme:
      config:
        - http01:
            ingressClass: nginx
          domains:
            - discordapp-clone.com
            - www.discordapp-clone.com    
